### ISSUE TITLE
Moustache missing in iterator

### ISSUE THREAD

**Issue by bbaassssiiee** [hudecof/ansible_tomcat#4]
https://github.com/hudecof/ansible_tomcat/blob/cd67ada565b9b2ceb5c9b845a36b1292372eccfc/tasks/setup-RedHat.yml#L5

Shouldn't this read:

```
with_items: "{{ tomcat_packages }}"
```

Error:

`
TASK [hudecof.tomcat : check packages (redhat)] ********************************
failed: [default] (item=[u'tomcat_packages']) => {"changed": false, "item": ["tomcat_packages"], "msg": "No package matching 'tomcat_packages' found available, installed or updated", "rc": 126, "results": ["No package matching 'tomcat_packages' found available, installed or updated"]}
	to retry, use: --limit @/tmp/ansible/playbook.retry
`

**Comment by hudecof** [comment]
tI havenôt used this role for a very long time, so some parts should not be valid with the new version of ansible.
I could try to take a ook on this role and update it.

**Comment by hudecof** [comment]
should be fixed in release/tag v0.1.1
